# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtcWeb', '0003_auto_20160622_1504'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
