# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:04
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtcWeb', '0002_auto_20160622_1326'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=765, unique=True),
        ),
    ]
